### ISSUE TITLE
Deprecated commands

### ISSUE THREAD

**Issue by wengh** [NuGet/setup-nuget#11]
When I run setup-nuget in my workflow, the following warnings appear:

```
Run NuGet/setup-nuget@v1.0.2
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Installed nuget.exe version 5.7.0
```

**Comment by dylan-smith** [comment]
I think to fix this all that is required is update the @actions library in the node_modules folder and commit it

**Comment by riverar** [comment]
Still seeing this in production, did this get released?

**Comment by zkat** [comment]
I just released v1.0.3. Everything should be good now. Can any of y'all confirm? @riverar? :)

**Comment by riverar** [comment]
@zkat Super, thanks! Will start a run now to verify.

**Comment by riverar** [comment]
@zkat Uh oh.

```Error: Cannot find module './utils'
Require stack:
- D:\a\_actions\NuGet\setup-nuget\v1\node_modules\@actions\core\lib\command.js
- D:\a\_actions\NuGet\setup-nuget\v1\node_modules\@actions\core\lib\core.js
- D:\a\_actions\NuGet\setup-nuget\v1\lib\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\a\_actions\NuGet\setup-nuget\v1\node_modules\@actions\core\lib\command.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\_actions\\NuGet\\setup-nuget\\v1\\node_modules\\@actions\\core\\lib\\command.js',
    'D:\\a\\_actions\\NuGet\\setup-nuget\\v1\\node_modules\\@actions\\core\\lib\\core.js',
    'D:\\a\\_actions\\NuGet\\setup-nuget\\v1\\lib\\main.js'
  ]```

**Comment by zkat** [comment]
@riverar This should be fixed now. Had a small hiccup upgrading the action template :)
