### ISSUE TITLE
Cannot find module './utils'

### ISSUE THREAD

**Issue by NaBian** [NuGet/setup-nuget#15]
9 days ago, everything was fine, while yesterday it went wrong in workflow, here is the log:
```
Run nuget/setup-nuget@master
  with:
    nuget-version: latest
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './utils'
Require stack:
- D:\a\_actions\nuget\setup-nuget\master\node_modules\@actions\core\lib\command.js
- D:\a\_actions\nuget\setup-nuget\master\node_modules\@actions\core\lib\core.js
- D:\a\_actions\nuget\setup-nuget\master\lib\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\a\_actions\nuget\setup-nuget\master\node_modules\@actions\core\lib\command.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\_actions\\nuget\\setup-nuget\\master\\node_modules\\@actions\\core\\lib\\command.js',
    'D:\\a\\_actions\\nuget\\setup-nuget\\master\\node_modules\\@actions\\core\\lib\\core.js',
    'D:\\a\\_actions\\nuget\\setup-nuget\\master\\lib\\main.js'
  ]
}
```

[yml file](https://github.com/HandyOrg/HandyControl/blob/master/.github/workflows/build.yml)

**Comment by zkat** [comment]
Something weird happened with `@actions/core`. I've reinstalled the dep and published v1.0.3. Everything should Just Work for you now. Can you confirm and close this issue?

**Comment by andrew-welker** [comment]
I'm having the same issue. I've got my workflow set to use it using the following step:

```
- name: Add nuget.exe
        uses: nuget/setup-nuget@v1
```

I'm rerunning the 2 latest jobs now, and I'll let update here.

**Comment by kstolte** [comment]
I'm also having the same issue. Everything was working fine for me as late as 2020-11-11 14:07 EST

```
Run nuget/setup-nuget@v1
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './utils'
Require stack:
- C:\actions-runner\_work\_actions\nuget\setup-nuget\v1\node_modules\@actions\core\lib\command.js
- C:\actions-runner\_work\_actions\nuget\setup-nuget\v1\node_modules\@actions\core\lib\core.js
- C:\actions-runner\_work\_actions\nuget\setup-nuget\v1\lib\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\actions-runner\_work\_actions\nuget\setup-nuget\v1\node_modules\@actions\core\lib\command.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\actions-runner\\_work\\_actions\\nuget\\setup-nuget\\v1\\node_modules\\@actions\\core\\lib\\command.js',
    'C:\\actions-runner\\_work\\_actions\\nuget\\setup-nuget\\v1\\node_modules\\@actions\\core\\lib\\core.js',
    'C:\\actions-runner\\_work\\_actions\\nuget\\setup-nuget\\v1\\lib\\main.js'
  ]
}
```

**Comment by tfaris** [comment]
Checking in with the same problem, my workflow definition already uses the following

```
    - name: nuget restore
      uses: nuget/setup-nuget@v1
```

**Comment by andrew-welker** [comment]
Still failing. Error is:
```
Error: Cannot find module './utils'
Require stack:
- D:\a\_actions\nuget\setup-nuget\v1\node_modules\@actions\core\lib\command.js
- D:\a\_actions\nuget\setup-nuget\v1\node_modules\@actions\core\lib\core.js
- D:\a\_actions\nuget\setup-nuget\v1\lib\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\a\_actions\nuget\setup-nuget\v1\node_modules\@actions\core\lib\command.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\_actions\\nuget\\setup-nuget\\v1\\node_modules\\@actions\\core\\lib\\command.js',
    'D:\\a\\_actions\\nuget\\setup-nuget\\v1\\node_modules\\@actions\\core\\lib\\core.js',
    'D:\\a\\_actions\\nuget\\setup-nuget\\v1\\lib\\main.js'
  ]
}
```

The kinda odd thing is that this worked just fine in a different repo about an hour ago (1 PM or so MST), but isn't working in a different repo in the same org.

**Comment by kstolte** [comment]
Hi @zkat did some digging the original issue was reported by someone using NuGet/setup-nuget@master while the rest of the commenters have our versions at `@v1`. so we didnt get the roll out of #12 until the release of 1.0.3.

Just trying to help!

**Comment by zkat** [comment]
Hm. I'll look into this today. Sorry for the hassle, folks.

**Comment by andrew-welker** [comment]
I just tried changing our workflow to had master instead of v1 and had the same issue.

**Comment by kstolte** [comment]
if anyone has something critical that depends on this repo you can pin to the previously released version of 1.0.2
to the following

```yml
    - name: Setting up nuget.exe
      uses: nuget/setup-nuget@v1.0.2
```

this is working successfully in my environment.

**Comment by maartenscholl** [comment]
> if anyone has something critical that depends on this repo you can pin to the previously released version of 1.0.2
> to the following
> 
> ```yaml
>     - name: Setting up nuget.exe
>       uses: nuget/setup-nuget@v1.0.2
> ```
> 
> this is working successfully in my environment.

Cheers, this allowed me to continue working in the mean time

**Comment by zkat** [comment]
https://github.com/NuGet/setup-nuget/pull/17 This might fix it.

**Comment by zkat** [comment]
gonna reopen this until everything is nice and published.

**Comment by zkat** [comment]
Alright, everything's released. @maartenscholl @andrew-welker @kstolte can any of you confirm that `v1` works for you now?

**Comment by JimBobSquarePants** [comment]
I'm now seeing 

```bash
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/NuGet/setup-nuget/v1/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/NuGet/setup-nuget/v1/lib/main.js:25:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/NuGet/setup-nuget/v1/lib/main.js' ]
}
```

**Comment by andrew-welker** [comment]
Got a build going now. I'll let you know.

**Comment by zkat** [comment]
I guess I'll need more time to look into this and play with it before declaring victory. For those coming in just now: just change `v1` to `v1.0.2` and you should be good for now.

**Comment by zkat** [comment]
Once more, with feeling: https://github.com/NuGet/setup-nuget/pull/20

**Comment by kstolte** [comment]
im pointing at main right now and #20 resolved it.

```
Run nuget/setup-nuget@main
Installed nuget.exe version 5.7.0
```

**Comment by zkat** [comment]
@kstolte awesome. Everything's published now, then 👍🏻

**Comment by JimBobSquarePants** [comment]
Looking good. Thanks for the quick turnaround ❤️

**Comment by NaBian** [comment]
thank you for your effort. 😆
